package com.pm.patientservice.exception;

import java.util.HashMap;
import java.util.Map;

import org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
public class GlobalExceptionHandler {

	@ExceptionHandler(MethodArgumentNotValidException.class)
	public ResponseEntity<Map<String,String>> handleValidateException(MethodArgumentNotValidException ex){
		Map<String,String> response = new HashMap<>();
		ex.getBindingResult().getFieldErrors().forEach(
				error -> response.put(error.getField(), error.getDefaultMessage())
		);
		return ResponseEntity.badRequest().body(response);
	}
	
	@ExceptionHandler(JdbcSQLIntegrityConstraintViolationException.class)
	public ResponseEntity<Map<String,String>> handleJdbcSQLIntegrityConstraintViolationException(JdbcSQLIntegrityConstraintViolationException ex){
		Map<String,String> response = new HashMap<>();
		response.put("error", "Got duplicatie entry in the database");
		return ResponseEntity.badRequest().body(response);
	}
	
	@ExceptionHandler(EmailAlreadyExistException.class)
	public ResponseEntity<Map<String,String>> handleEmailAlreadyExistException(EmailAlreadyExistException ex){
		Map<String,String> response = new HashMap<>();
		response.put("error", "Patient with this email already exist");
		return ResponseEntity.badRequest().body(response);
	}
}
